version: '3.8'

services:
  lstwebstg:
    image: python:3.9-slim
    container_name: lstwebstg
    working_dir: /app
    volumes:
      - ./:/app
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env
    networks:
      - lstnetstg
    depends_on:
      - lstdbstg

  lstdbstg:
    image: postgres:13
    container_name: lstdbstg
    env_file:
      - .env
    volumes:
      - lst_pg_data_stag:/var/lib/postgresql/data
    networks:
      - lstnetstg
networks:
  lstnetstg:
    driver: bridge

volumes:
  lst_pg_data_stag:
    external: true
