version: '3.8'

services:
  lstwebstg:
    image: python:3.9-slim
    container_name: flask_app_staging
    working_dir: /app
    volumes:
      - .:/app
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env
    networks:
      - lstmknetstag
    depends_on:
      - lstdbstg

  lstdbstg:
    image: postgres:13
    container_name: postgres_db_staging
    env_file:
      - .env
    volumes:
      - lst_pg_data_stag:/var/lib/postgresql/data
    networks:
      - lstmknetstag

networks:
  lstmknetstag:
    driver: bridge

volumes:
  lst_pg_data_stag:
    external: true
